name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Surge
        run: npm install --global surge

      - name: Desplegar a Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          surge ./ --domain primer-parcial-mariel141.surge.sh --token $SURGE_TOKEN